server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///guestbook?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false


